import Head from "next/head";
import { Inter } from "next/font/google";
import SimulationForm from "@/components/SimulationForm";
import GameList from "@/components/GameList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>War Card Game Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-64 pt-5">
          <h1 className="text-3xl mb-3">War Card Game Simulator</h1>
          <SimulationForm />
          <GameList />
        </div>
      </main>
    </>
  );
}
