import LeaderboardTable from "@/components/LeaderboardTable";
import Head from "next/head";
import Link from "next/link";

export default function LeaderboardPage() {
  return (
    <>
      <Head>
        <title>War Card Game Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-64 pt-5">
          <p className="mb-4 text-blue-600 hover:text-blue-800">
            <Link href="/">Return to Home</Link>
          </p>
          <LeaderboardTable />
        </div>
      </main>
    </>
  );
}
